"""Inicio limpio

Revision ID: e006d822bd38
Revises: 
Create Date: 2025-12-30 17:10:46.572991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e006d822bd38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brands_name'), ['name'], unique=True)

    op.create_table('graphics_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graphics_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graphics_cards_name'), ['name'], unique=True)

    op.create_table('operating_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operating_systems', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operating_systems_name'), ['name'], unique=True)

    op.create_table('processors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('processors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processors_name'), ['name'], unique=True)

    op.create_table('ram_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ram_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ram_types_name'), ['name'], unique=True)

    op.create_table('screens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screens_name'), ['name'], unique=True)

    op.create_table('storage_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('storage_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storage_types_name'), ['name'], unique=True)

    op.create_table('stores',
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_name'), ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('laptop_models',
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('laptop_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_laptop_models_name'), ['name'], unique=True)

    op.create_table('locations',
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_name'), ['name'], unique=True)

    op.create_table('laptops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('processor_id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=False),
    sa.Column('screen_id', sa.Integer(), nullable=False),
    sa.Column('graphics_card_id', sa.Integer(), nullable=False),
    sa.Column('storage_id', sa.Integer(), nullable=False),
    sa.Column('ram_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('npu', sa.String(length=200), nullable=True),
    sa.Column('storage_upgradeable', sa.Boolean(), nullable=True),
    sa.Column('ram_upgradeable', sa.Boolean(), nullable=True),
    sa.Column('purchase_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('min_alert', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('GAMER', 'WORKING', 'HOME', name='laptopcategory'), nullable=False),
    sa.Column('condition', sa.Enum('NEW', 'USED', 'REFURBISHED', name='laptopcondition'), nullable=False),
    sa.Column('aesthetic_grade', sa.Enum('A_PLUS', 'A', 'B', 'C', name='aestheticgrade'), nullable=True),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('sale_date', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ai_recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['graphics_card_id'], ['graphics_cards.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['laptop_models.id'], ),
    sa.ForeignKeyConstraint(['os_id'], ['operating_systems.id'], ),
    sa.ForeignKeyConstraint(['processor_id'], ['processors.id'], ),
    sa.ForeignKeyConstraint(['ram_id'], ['ram_types.id'], ),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], ),
    sa.ForeignKeyConstraint(['storage_id'], ['storage_types.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('laptops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_laptops_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_laptops_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_laptops_condition'), ['condition'], unique=False)
        batch_op.create_index(batch_op.f('ix_laptops_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_laptops_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_laptops_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_laptops_sku'), ['sku'], unique=True)

    op.create_table('laptop_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laptop_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['laptop_id'], ['laptops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('laptop_id', 'order', name='uq_laptop_image_order')
    )
    with op.batch_alter_table('laptop_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_laptop_images_laptop_id'), ['laptop_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptop_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_laptop_images_laptop_id'))

    op.drop_table('laptop_images')
    with op.batch_alter_table('laptops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_laptops_sku'))
        batch_op.drop_index(batch_op.f('ix_laptops_model_id'))
        batch_op.drop_index(batch_op.f('ix_laptops_entry_date'))
        batch_op.drop_index(batch_op.f('ix_laptops_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_laptops_condition'))
        batch_op.drop_index(batch_op.f('ix_laptops_category'))
        batch_op.drop_index(batch_op.f('ix_laptops_brand_id'))

    op.drop_table('laptops')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_name'))

    op.drop_table('locations')
    with op.batch_alter_table('laptop_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_laptop_models_name'))

    op.drop_table('laptop_models')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_name'))

    op.drop_table('stores')
    with op.batch_alter_table('storage_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storage_types_name'))

    op.drop_table('storage_types')
    with op.batch_alter_table('screens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screens_name'))

    op.drop_table('screens')
    with op.batch_alter_table('ram_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ram_types_name'))

    op.drop_table('ram_types')
    with op.batch_alter_table('processors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processors_name'))

    op.drop_table('processors')
    with op.batch_alter_table('operating_systems', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operating_systems_name'))

    op.drop_table('operating_systems')
    with op.batch_alter_table('graphics_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graphics_cards_name'))

    op.drop_table('graphics_cards')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brands_name'))

    op.drop_table('brands')
    # ### end Alembic commands ###
